# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: VietnameseTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 3
  - name: rasa_nlu_examples.featurizers.dense.BytePairFeaturizer
    lang: vi
    vs: 1000
    dim: 25
  - name: LanguageModelFeaturizer
    model_name: "roberta"
    model_weights: "vinai/phobert-base"
  - name: DIETClassifier
    epochs: 200
    constrain_similarities: true
  - name: "EntitySynonymMapper"
  - name: ResponseSelector
    epochs: 100
  

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
